name: check main.py

on:
  push:
    branches:
      - master
    
  schedule:
    - cron: '* * 1 * 1'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          
      - name: Build .exe
        run: pyinstaller -y  main.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy .exe
        uses: actions/upload-artifact@v2
        with:
          name: main-exe
          path: ./dist/main
          
     


    
